// Verification solutions for the two offered database engines. These are not sent
// to the browser; fixture answers are calculated separately by JavaScript.
export function playlistQuery(problem,engine) {
  const mysql=engine==='mysql';
  const choose=(a,b)=>mysql?a:b;
  const year=value=>choose(`YEAR(${value})`,`EXTRACT(YEAR FROM ${value})`);
  const difference=(a,b)=>choose(`DATEDIFF(${a},${b})`,`(${a}::date-${b}::date)`);
  const seconds=(a,b)=>choose(`TIMESTAMPDIFF(SECOND,${a},${b})`,`EXTRACT(EPOCH FROM (${b}-${a}))`);
  const monthStart=n=>choose(`DATE_ADD('2020-01-01',INTERVAL (${n}) MONTH)`,`(DATE '2020-01-01'+(${n})*INTERVAL '1 month')`);
  const calendar=`WITH RECURSIVE months(month) AS (SELECT 1 UNION ALL SELECT month+1 FROM months WHERE month<12)`;
  const during=`r.requested_at>=${monthStart('m.month-1')} AND r.requested_at<${monthStart('m.month')}`;
  const sumIf=condition=>`SUM(CASE WHEN ${condition} THEN 1 ELSE 0 END)`;
  const overrides={
    1479: `SELECT i.item_category AS category,${['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'].map((day,i)=>`SUM(CASE WHEN ${choose('WEEKDAY(o.order_date)+1','EXTRACT(ISODOW FROM o.order_date)')}=${i+1} THEN o.quantity ELSE 0 END) AS ${day}`).join(',')} FROM Items i LEFT JOIN Orders o ON o.item_id=i.item_id GROUP BY i.item_category ORDER BY category`,
    569: `WITH ranked AS (SELECT *,ROW_NUMBER() OVER(PARTITION BY company ORDER BY salary,id) AS rn,COUNT(*) OVER(PARTITION BY company) AS n FROM Employee) SELECT id,company,salary FROM ranked WHERE rn BETWEEN n/2.0 AND n/2.0+1`,
    615: `WITH salaries AS (SELECT ${choose("DATE_FORMAT(pay_date,'%Y-%m')","TO_CHAR(pay_date,'YYYY-MM')")} AS pay_month,e.department_id,s.amount FROM Salary s JOIN Employee e ON e.employee_id=s.employee_id), averages AS (SELECT *,AVG(amount) OVER(PARTITION BY pay_month) AS company_avg,AVG(amount) OVER(PARTITION BY pay_month,department_id) AS dept_avg FROM salaries) SELECT DISTINCT pay_month,department_id,CASE WHEN dept_avg>company_avg THEN 'higher' WHEN dept_avg<company_avg THEN 'lower' ELSE 'same' END AS comparison FROM averages`,
    2199: `WITH hits AS (SELECT DISTINCT p.post_id,k.topic_id FROM Posts p LEFT JOIN Keywords k ON LOWER(CONCAT(' ',p.content,' ')) LIKE CONCAT('% ',LOWER(k.word),' %')) SELECT post_id,COALESCE(${choose("GROUP_CONCAT(topic_id ORDER BY topic_id SEPARATOR ',')","STRING_AGG(topic_id::text,',' ORDER BY topic_id)")},'Ambiguous!') AS topic FROM hits GROUP BY post_id`,
    1412: `WITH extremes AS (SELECT *,MIN(score) OVER(PARTITION BY exam_id) AS lo,MAX(score) OVER(PARTITION BY exam_id) AS hi FROM Exam) SELECT s.student_id,s.student_name FROM Student s WHERE EXISTS(SELECT 1 FROM Exam e WHERE e.student_id=s.student_id) AND NOT EXISTS(SELECT 1 FROM extremes e WHERE e.student_id=s.student_id AND (score=lo OR score=hi)) ORDER BY s.student_id`,
    1225: `WITH days AS (SELECT fail_date AS dt,'failed' AS state FROM Failed WHERE fail_date BETWEEN '2019-01-01' AND '2019-12-31' UNION ALL SELECT success_date,'succeeded' FROM Succeeded WHERE success_date BETWEEN '2019-01-01' AND '2019-12-31'), grouped AS (SELECT *,${difference('dt',"'2019-01-01'")}-${choose('CAST(ROW_NUMBER() OVER(PARTITION BY state ORDER BY dt) AS SIGNED)','ROW_NUMBER() OVER(PARTITION BY state ORDER BY dt)')} AS grp FROM days) SELECT state AS period_state,MIN(dt) AS start_date,MAX(dt) AS end_date FROM grouped GROUP BY state,grp ORDER BY start_date`,
    3057: `WITH allocation AS (SELECT p.*,e.name,AVG(workload) OVER(PARTITION BY e.team) AS average_workload FROM Project p JOIN Employees e ON e.employee_id=p.employee_id) SELECT employee_id,project_id,name AS employee_name,workload AS project_workload FROM allocation WHERE workload>average_workload ORDER BY employee_id,project_id`,
    2793: `WITH ranked AS (SELECT p.*,f.capacity,ROW_NUMBER() OVER(PARTITION BY p.flight_id ORDER BY booking_time) AS rn FROM Passengers p JOIN Flights f ON f.flight_id=p.flight_id) SELECT passenger_id,CASE WHEN rn<=capacity THEN 'Confirmed' ELSE 'Waitlist' END AS Status FROM ranked ORDER BY passenger_id`,
    1972: `WITH calls_both AS (SELECT caller_id,recipient_id,call_time FROM Calls UNION ALL SELECT recipient_id,caller_id,call_time FROM Calls), ranked AS (SELECT caller_id,FIRST_VALUE(recipient_id) OVER(PARTITION BY caller_id,DATE(call_time) ORDER BY call_time) AS first_contact,FIRST_VALUE(recipient_id) OVER(PARTITION BY caller_id,DATE(call_time) ORDER BY call_time DESC) AS last_contact FROM calls_both) SELECT DISTINCT caller_id AS user_id FROM ranked WHERE first_contact=last_contact`,
    2173: `WITH numbered AS (SELECT *,SUM(CASE WHEN result='Win' THEN 0 ELSE 1 END) OVER(PARTITION BY player_id ORDER BY match_day) AS grp FROM Matches), streaks AS (SELECT player_id,grp,${sumIf("result='Win'")} AS wins FROM numbered GROUP BY player_id,grp) SELECT player_id,MAX(wins) AS longest_streak FROM streaks GROUP BY player_id`,
    2474: `WITH yearly AS (SELECT customer_id,${year('order_date')} AS yr,SUM(price) AS total FROM Orders GROUP BY customer_id,${year('order_date')}), previous AS (SELECT *,LAG(yr) OVER(PARTITION BY customer_id ORDER BY yr) AS prev_year,LAG(total) OVER(PARTITION BY customer_id ORDER BY yr) AS prev_total FROM yearly) SELECT customer_id FROM previous GROUP BY customer_id HAVING SUM(CASE WHEN prev_year IS NOT NULL AND (yr<>prev_year+1 OR total<=prev_total) THEN 1 ELSE 0 END)=0`,
    3214: `WITH yearly AS (SELECT product_id,${year('transaction_date')} AS yr,SUM(spend) AS amount FROM user_transactions GROUP BY product_id,${year('transaction_date')}) SELECT a.yr AS year,a.product_id,a.amount AS curr_year_spend,b.amount AS prev_year_spend,ROUND(100.0*(a.amount-b.amount)/NULLIF(b.amount,0),2) AS yoy_rate FROM yearly a LEFT JOIN yearly b ON a.product_id=b.product_id AND a.yr=b.yr+1 ORDER BY a.product_id,a.yr`,
    3052: `WITH totals AS (SELECT SUM(CASE WHEN item_type='prime_eligible' THEN square_footage ELSE 0 END) AS prime_area,${sumIf("item_type='prime_eligible'")} AS prime_count,SUM(CASE WHEN item_type='not_prime' THEN square_footage ELSE 0 END) AS other_area,${sumIf("item_type='not_prime'")} AS other_count FROM Inventory), batches AS (SELECT *,COALESCE(FLOOR(500000.0000000000/NULLIF(prime_area,0)),0) AS prime_batches FROM totals) SELECT 'prime_eligible' AS item_type,COALESCE(prime_batches*prime_count,0) AS item_count FROM batches UNION ALL SELECT 'not_prime',COALESCE(FLOOR((500000.0000000000-prime_batches*COALESCE(prime_area,0))/NULLIF(other_area,0))*other_count,0) FROM batches ORDER BY item_count DESC`,
    2991: `WITH totals AS (SELECT country,winery,SUM(points) AS points FROM Wineries GROUP BY country,winery), ranked AS (SELECT *,ROW_NUMBER() OVER(PARTITION BY country ORDER BY points DESC,winery) AS rn FROM totals) SELECT country,MAX(CASE WHEN rn=1 THEN CONCAT(winery,' (',points,')') END) AS top_winery,COALESCE(MAX(CASE WHEN rn=2 THEN CONCAT(winery,' (',points,')') END),'No second winery') AS second_winery,COALESCE(MAX(CASE WHEN rn=3 THEN CONCAT(winery,' (',points,')') END),'No third winery') AS third_winery FROM ranked GROUP BY country ORDER BY country`,
    262: `SELECT request_at AS Day,ROUND(AVG(CASE WHEN t.status='completed' THEN 0.0 ELSE 1.0 END),2) AS ${choose('`Cancellation Rate`','"Cancellation Rate"')} FROM Trips t JOIN Users c ON c.users_id=t.client_id JOIN Users d ON d.users_id=t.driver_id WHERE c.banned='No' AND d.banned='No' AND request_at BETWEEN '2013-10-01' AND '2013-10-03' GROUP BY request_at`,
    1097: `WITH players AS (SELECT player_id,MIN(event_date) AS install_dt FROM Activity GROUP BY player_id), retained AS (SELECT p.*,CASE WHEN EXISTS(SELECT 1 FROM Activity a WHERE a.player_id=p.player_id AND ${difference('a.event_date','p.install_dt')}=1) THEN 1.0 ELSE 0.0 END AS retained FROM players p) SELECT install_dt,COUNT(*) AS installs,ROUND(AVG(retained),2) AS day1_retention FROM retained GROUP BY install_dt`,
    2720: `WITH all_friends AS (SELECT user1,user2 FROM Friends UNION SELECT user2,user1 FROM Friends) SELECT user1,ROUND(COUNT(*)*100.0/(SELECT COUNT(DISTINCT user1) FROM all_friends),2) AS percentage_popularity FROM all_friends GROUP BY user1 ORDER BY user1`,
    2752: `WITH numbered AS (SELECT customer_id,transaction_date,${difference('transaction_date',"'2000-01-01'")}-ROW_NUMBER() OVER(PARTITION BY customer_id ORDER BY transaction_date) AS grp FROM Transactions), streaks AS (SELECT customer_id,grp,COUNT(*) AS n FROM numbered GROUP BY customer_id,grp) SELECT DISTINCT customer_id FROM streaks WHERE n=(SELECT MAX(n) FROM streaks) ORDER BY customer_id`,
    571: `WITH cumulative AS (SELECT *,SUM(frequency) OVER(ORDER BY num) AS before_count,SUM(frequency) OVER(ORDER BY num DESC) AS after_count,SUM(frequency) OVER() AS n FROM Numbers) SELECT ROUND(AVG(num*1.0),1) AS median FROM cumulative WHERE before_count>=n/2.0 AND after_count>=n/2.0`,
    1127: `WITH platforms AS (SELECT DISTINCT spend_date,'desktop' AS platform FROM Spending UNION SELECT DISTINCT spend_date,'mobile' FROM Spending UNION SELECT DISTINCT spend_date,'both' FROM Spending), users AS (SELECT user_id,spend_date,SUM(amount) AS amount,CASE WHEN COUNT(*)=2 THEN 'both' ELSE MIN(platform) END AS platform FROM Spending GROUP BY user_id,spend_date) SELECT p.spend_date,p.platform,COALESCE(SUM(u.amount),0) AS total_amount,COUNT(u.user_id) AS total_users FROM platforms p LEFT JOIN users u ON p.spend_date=u.spend_date AND p.platform=u.platform GROUP BY p.spend_date,p.platform`,
    1635: `${calendar} SELECT m.month,(SELECT COUNT(*) FROM Drivers d WHERE d.join_date<${monthStart('m.month')}) AS active_drivers,(SELECT COUNT(*) FROM Rides r JOIN AcceptedRides a ON a.ride_id=r.ride_id WHERE ${during}) AS accepted_rides FROM months m ORDER BY m.month`,
    1645: `${calendar} SELECT m.month,COALESCE(ROUND(100.0*(SELECT COUNT(DISTINCT a.driver_id) FROM Rides r JOIN AcceptedRides a ON a.ride_id=r.ride_id WHERE ${during})/NULLIF((SELECT COUNT(*) FROM Drivers d WHERE d.join_date<${monthStart('m.month')}),0),2),0) AS working_percentage FROM months m ORDER BY m.month`,
    1651: `${calendar}, monthly AS (SELECT m.month,COALESCE(SUM(a.ride_distance),0) AS distance,COALESCE(SUM(a.ride_duration),0) AS duration FROM months m LEFT JOIN Rides r ON ${during} LEFT JOIN AcceptedRides a ON a.ride_id=r.ride_id GROUP BY m.month), averages AS (SELECT month,ROUND(AVG(distance) OVER(ORDER BY month ROWS BETWEEN CURRENT ROW AND 2 FOLLOWING),2) AS average_ride_distance,ROUND(AVG(duration) OVER(ORDER BY month ROWS BETWEEN CURRENT ROW AND 2 FOLLOWING),2) AS average_ride_duration FROM monthly) SELECT * FROM averages WHERE month<=10 ORDER BY month`,
    3384: `SELECT f.team_name,CASE WHEN time_stamp<='45:00' THEN 1 ELSE 2 END AS half_number,SUM(CASE WHEN f.team_name=t.team_name THEN 1 ELSE -1 END) AS dominance FROM Passes p JOIN Teams f ON f.player_id=p.pass_from JOIN Teams t ON t.player_id=p.pass_to GROUP BY f.team_name,CASE WHEN time_stamp<='45:00' THEN 1 ELSE 2 END ORDER BY team_name,half_number`,
    3268: `WITH counts AS (SELECT a.employee_id,a.start_time,COUNT(*) AS n FROM EmployeeShifts a JOIN EmployeeShifts b ON a.employee_id=b.employee_id AND DATE(a.start_time)=DATE(b.start_time) AND b.start_time<=a.start_time AND b.end_time>a.start_time GROUP BY a.employee_id,a.start_time), pair_overlaps AS (SELECT a.employee_id,SUM(FLOOR(${seconds('b.start_time','LEAST(a.end_time,b.end_time)')}/60)) AS duration FROM EmployeeShifts a JOIN EmployeeShifts b ON a.employee_id=b.employee_id AND DATE(a.start_time)=DATE(b.start_time) AND a.start_time<b.start_time AND a.end_time>b.start_time GROUP BY a.employee_id) SELECT c.employee_id,MAX(c.n) AS max_overlapping_shifts,COALESCE(MAX(o.duration),0) AS total_overlap_duration FROM counts c LEFT JOIN pair_overlaps o ON o.employee_id=c.employee_id GROUP BY c.employee_id ORDER BY c.employee_id`,
    618: `WITH ranked AS (SELECT *,ROW_NUMBER() OVER(PARTITION BY continent ORDER BY name) AS rn FROM Student) SELECT MAX(CASE WHEN continent='America' THEN name END) AS America,MAX(CASE WHEN continent='Asia' THEN name END) AS Asia,MAX(CASE WHEN continent='Europe' THEN name END) AS Europe FROM ranked GROUP BY rn ORDER BY rn`,
    3673: `SELECT session_id,user_id,FLOOR(${seconds('MIN(event_timestamp)','MAX(event_timestamp)')}/60) AS session_duration_minutes,${sumIf("event_type='scroll'")} AS scroll_count FROM app_events GROUP BY session_id,user_id HAVING ${seconds('MIN(event_timestamp)','MAX(event_timestamp)')}>1800 AND ${sumIf("event_type='scroll'")}>=5 AND ${sumIf("event_type='click'")}*1.0/NULLIF(${sumIf("event_type='scroll'")},0)<0.20 AND ${sumIf("event_type='purchase'")}=0 ORDER BY scroll_count DESC,session_id`,
    3554: `WITH categories AS (SELECT DISTINCT p.user_id,i.category FROM ProductPurchases p JOIN ProductInfo i ON i.product_id=p.product_id) SELECT a.category AS category1,b.category AS category2,COUNT(DISTINCT a.user_id) AS customer_count FROM categories a JOIN categories b ON a.user_id=b.user_id AND a.category<b.category GROUP BY a.category,b.category HAVING COUNT(DISTINCT a.user_id)>=3 ORDER BY customer_count DESC,category1,category2`,
    2994: `WITH fridays AS (SELECT 1 AS week_of_month,CAST('2023-11-03' AS DATE) AS purchase_date UNION ALL SELECT 2,CAST('2023-11-10' AS DATE) UNION ALL SELECT 3,CAST('2023-11-17' AS DATE) UNION ALL SELECT 4,CAST('2023-11-24' AS DATE)) SELECT f.week_of_month,f.purchase_date,COALESCE(SUM(p.amount_spend),0) AS total_amount FROM fridays f LEFT JOIN Purchases p ON p.purchase_date=f.purchase_date GROUP BY f.week_of_month,f.purchase_date ORDER BY f.week_of_month`,
    2494: `WITH previous AS (SELECT *,MAX(end_day) OVER(PARTITION BY hall_id ORDER BY start_day,end_day ROWS BETWEEN UNBOUNDED PRECEDING AND 1 PRECEDING) AS prior_end FROM HallEvents), boundaries AS (SELECT *,CASE WHEN prior_end>=start_day THEN 0 ELSE 1 END AS boundary FROM previous), grouped AS (SELECT *,SUM(boundary) OVER(PARTITION BY hall_id ORDER BY start_day,end_day ROWS UNBOUNDED PRECEDING) AS grp FROM boundaries) SELECT hall_id,MIN(start_day) AS start_day,MAX(end_day) AS end_day FROM grouped GROUP BY hall_id,grp`,
    3060: `SELECT DISTINCT a.user_id FROM Sessions a JOIN Sessions b ON a.user_id=b.user_id AND a.session_type=b.session_type AND a.session_id<>b.session_id WHERE b.session_start>=a.session_end AND ${seconds('a.session_end','b.session_start')}<=43200 ORDER BY a.user_id`,
    3832: `WITH daily AS (SELECT user_id,action_date,MIN(action) AS action FROM activity GROUP BY user_id,action_date HAVING COUNT(*)=1), numbered AS (SELECT *,${difference('action_date',"'2000-01-01'")}-ROW_NUMBER() OVER(PARTITION BY user_id,action ORDER BY action_date) AS grp FROM daily), streaks AS (SELECT user_id,action,COUNT(*) AS streak_length,MIN(action_date) AS start_date,MAX(action_date) AS end_date FROM numbered GROUP BY user_id,action,grp HAVING COUNT(*)>=5), ranked AS (SELECT *,ROW_NUMBER() OVER(PARTITION BY user_id ORDER BY streak_length DESC,start_date,action) AS rn FROM streaks) SELECT user_id,action,streak_length,start_date,end_date FROM ranked WHERE rn=1 ORDER BY streak_length DESC,user_id`,
    3617: `WITH ordered AS (SELECT *,LAG(session_date) OVER(PARTITION BY student_id ORDER BY session_date,session_id) AS previous_date FROM study_sessions), grouped AS (SELECT *,SUM(CASE WHEN previous_date IS NULL OR ${difference('session_date','previous_date')}>2 THEN 1 ELSE 0 END) OVER(PARTITION BY student_id ORDER BY session_date,session_id) AS grp FROM ordered), positions AS (SELECT *,ROW_NUMBER() OVER(PARTITION BY student_id,grp ORDER BY session_date,session_id) AS rn FROM grouped), summaries AS (SELECT student_id,grp,COUNT(DISTINCT subject) AS cycle_length,COUNT(*) AS n,SUM(hours_studied) AS hours FROM positions GROUP BY student_id,grp), valid AS (SELECT *,ROW_NUMBER() OVER(PARTITION BY student_id ORDER BY cycle_length DESC,hours DESC,grp) AS choice FROM summaries g WHERE cycle_length>=3 AND n>=2*cycle_length AND NOT EXISTS(SELECT 1 FROM positions a JOIN positions b ON a.student_id=b.student_id AND a.grp=b.grp AND b.rn=MOD(a.rn-1,g.cycle_length)+1 WHERE a.student_id=g.student_id AND a.grp=g.grp AND a.subject<>b.subject)) SELECT s.student_id,s.student_name,s.major,v.cycle_length,v.hours AS total_study_hours FROM valid v JOIN students s ON s.student_id=v.student_id WHERE choice=1 ORDER BY cycle_length DESC,total_study_hours DESC`,
    3451: choose(`SELECT ip,COUNT(*) AS invalid_count FROM logs WHERE NOT REGEXP_LIKE(ip,'^(0|[1-9][0-9]{0,2})[.](0|[1-9][0-9]{0,2})[.](0|[1-9][0-9]{0,2})[.](0|[1-9][0-9]{0,2})$') OR CAST(SUBSTRING_INDEX(ip,'.',1) AS UNSIGNED)>255 OR CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(ip,'.',2),'.',-1) AS UNSIGNED)>255 OR CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(ip,'.',3),'.',-1) AS UNSIGNED)>255 OR CAST(SUBSTRING_INDEX(ip,'.',-1) AS UNSIGNED)>255 GROUP BY ip ORDER BY invalid_count DESC,ip DESC`,`SELECT ip,COUNT(*) AS invalid_count FROM logs WHERE CASE WHEN ip ~ '^(0|[1-9][0-9]{0,2})[.](0|[1-9][0-9]{0,2})[.](0|[1-9][0-9]{0,2})[.](0|[1-9][0-9]{0,2})$' THEN GREATEST(split_part(ip,'.',1)::integer,split_part(ip,'.',2)::integer,split_part(ip,'.',3)::integer,split_part(ip,'.',4)::integer)>255 ELSE TRUE END GROUP BY ip ORDER BY invalid_count DESC,ip DESC`),
    3368: choose(`WITH RECURSIVE letters(content_id,original_text,pos,converted_text) AS (SELECT content_id,content_text,1,CAST('' AS CHAR(2000)) FROM user_content UNION ALL SELECT content_id,original_text,pos+1,CONCAT(converted_text,CASE WHEN pos=1 OR SUBSTRING(original_text,pos-1,1)=' ' THEN UPPER(SUBSTRING(original_text,pos,1)) ELSE LOWER(SUBSTRING(original_text,pos,1)) END) FROM letters WHERE pos<=CHAR_LENGTH(original_text)) SELECT content_id,original_text,converted_text FROM letters WHERE pos=CHAR_LENGTH(original_text)+1`,`SELECT content_id,content_text AS original_text,INITCAP(content_text) AS converted_text FROM user_content`),
  };
  return overrides[problem.number]||problem.referenceSql;
}
