import React, { useMemo, useState } from 'react';
import { ArrowLeft, ArrowRight, BookOpen, Braces, Check, CircleCheck, Code2, LoaderCircle, Search, ShieldCheck, Sparkles, Trophy, UserRound } from 'lucide-react';
import GoogleButton from './GoogleButton.jsx';
import { validateProfile } from '../shared/profile.mjs';
import './account-pages.css';

export function LoginPage({ onGoogle, onGuest, error, questionCount }) {
  return <main className="welcome-page">
    <div className="welcome-top"><a className="brand" href="/login"><span className="brand-mark"><Braces size={22}/></span><span>queryroom<span className="brand-period">.</span></span></a><span>A space to think in SQL.</span></div>
    <div className="welcome-layout">
      <section className="welcome-story" aria-label="About Queryroom"><div className="dashboard-eyebrow"><span/> LESS SCROLLING. MORE SOLVING.</div><h1>Good at SQL?<br/><span>Get even better.</span></h1><p className="welcome-lead"><strong>Practise real SQL questions. Build your confidence. Make your next interview count.</strong></p><p className="welcome-description">Your own space to write queries, test ideas, and see your progress grow. One question at a time.</p>
        <div className="welcome-features"><div><BookOpen size={19}/><span><strong>{questionCount} SQL practice questions</strong><small>Explore the collection at your own pace.</small></span></div><div><Code2 size={19}/><span><strong>Real MySQL & PostgreSQL</strong><small>Run your queries and learn from every result.</small></span></div><div><CircleCheck size={19}/><span><strong>Every little win, saved</strong><small>Track solved questions, drafts, and bookmarks.</small></span></div></div>
        <div className="welcome-code" aria-hidden="true"><div><span/><span/><span/><small>your_next_step.sql</small></div><code><em>SELECT</em> confidence, new_skills<br/><em>FROM</em> daily_practice<br/><em>WHERE</em> curiosity = <b>true</b>;</code><p><Check size={13}/> A little practice goes a long way.</p></div>
      </section>
      <section className="welcome-card" aria-labelledby="welcome-title"><div className="welcome-card-icon"><Sparkles size={25}/></div><span className="dashboard-eyebrow">YOUR NEXT CHAPTER</span><h2 id="welcome-title">Make room for progress.</h2><p>Sign in or create your account with Google.<br/>Your practice comes with you.</p>
        {error && <div className="account-error" role="alert">{error}</div>}
        <GoogleButton onClick={onGoogle}/><div className="welcome-divider"><span/>or<span/></div><button className="guest-choice" onClick={onGuest}><UserRound size={18}/>Continue as guest<ArrowRight size={17}/></button><p className="guest-choice-note">Just here to practise? Jump right in.<br/>Guest progress is saved in this browser.</p><div className="welcome-reassurance"><ShieldCheck size={16}/><span>No password to remember.<br/>One Google account for sign-in and sign-up.</span></div>
      </section>
    </div><footer className="welcome-footer"><span>Small steps. Real progress.</span><span>Made for your next “aha.”</span></footer>
  </main>;
}

export function ProfileForm({ user, onSave, onCancel, editing = false }) {
  const [fields, setFields] = useState({username: user.username || '', fullName: user.fullName || user.name || '', age: user.age ?? '', profession: user.profession || ''});
  const [busy, setBusy] = useState(false), [error, setError] = useState('');
  function change(key, value) { setFields(previous => ({...previous, [key]: value})); setError(''); }
  async function submit(event) {
    event.preventDefault(); if (busy) return;
    setError(''); setBusy(true);
    try { await onSave(validateProfile({...fields, age: fields.age === '' ? NaN : Number(fields.age)})); }
    catch (failure) { setError(failure.message || 'Your profile could not be saved. Please try again.'); }
    finally { setBusy(false); }
  }
  return <form className="profile-form" onSubmit={submit}>
    <label>Username<div className="username-input"><span>@</span><input aria-label="Username" value={fields.username} onChange={e => change('username', e.target.value.toLowerCase())} autoComplete="username" autoCapitalize="none" spellCheck={false} minLength={3} maxLength={24} pattern="[a-z][a-z0-9_]{2,23}" required placeholder="your_username" disabled={busy}/></div><small>Unique to you. 3–24 letters, numbers, or underscores. Start with a letter.</small></label>
    <label>Full name<input aria-label="Full name" value={fields.fullName} onChange={e => change('fullName', e.target.value)} autoComplete="name" maxLength={100} required placeholder="Your full name" disabled={busy}/></label>
    <div className="profile-form-row"><label>Age<input aria-label="Age" type="number" inputMode="numeric" min="1" max="120" step="1" value={fields.age} onChange={e => change('age', e.target.value)} required placeholder="Age" disabled={busy}/></label><label>Profession<input aria-label="Profession" value={fields.profession} onChange={e => change('profession', e.target.value)} autoComplete="organization-title" maxLength={80} required placeholder="e.g. Student, Data analyst" disabled={busy}/></label></div>
    {error && <div className="account-error" role="alert">{error}</div>}
    <div className="profile-form-actions">{onCancel && <button className="secondary-button" type="button" onClick={onCancel} disabled={busy}>Cancel</button>}<button className="primary-button" type="submit" disabled={busy}>{busy ? <LoaderCircle size={17} className="spin"/> : editing ? <Check size={17}/> : <ArrowRight size={17}/>} {busy ? 'Saving…' : editing ? 'Save changes' : 'Save and continue'}</button></div>
  </form>;
}

export function OnboardingPage({ user, onSave, onSignOut }) {
  return <main className="onboarding-page"><div className="onboarding-card"><div className="onboarding-progress"><span><Check size={13}/> Google connected</span><i/><strong>Make it yours</strong></div><div className="welcome-card-icon"><UserRound size={25}/></div><div className="dashboard-eyebrow">A QUICK INTRODUCTION</div><h1>Welcome to your<br/><span>SQL practice space.</span></h1><p>Choose a username and tell us a little about yourself. You only need to do this once.</p><ProfileForm user={user} onSave={onSave}/><div className="onboarding-account"><span>Signed in as <strong>{user.email}</strong></span><button onClick={onSignOut}>Use another account</button></div><p className="profile-privacy"><ShieldCheck size={13}/> Your age and personal details stay in your account.</p></div></main>;
}

export function ProfilePage({ user, problems, progress, onOpen, onDashboard, onEdit }) {
  const [search, setSearch] = useState(''), [tab, setTab] = useState('solved'), [difficulty, setDifficulty] = useState('all');
  const solved = problems.filter(p => progress[p.slug]?.solved);
  const history = useMemo(() => problems.flatMap(p => (progress[p.slug]?.submissions || []).map(s => ({...s, problem: p}))).sort((a,b) => new Date(b.date)-new Date(a.date)), [problems, progress]);
  const filtered = solved.filter(p => `${p.title} ${p.number}`.toLowerCase().includes(search.toLowerCase()) && (difficulty === 'all' || p.difficulty.toLowerCase() === difficulty));
  const percent = Math.round(solved.length / Math.max(problems.length, 1) * 100);
  return <main className="profile-page"><div className="profile-inner"><button className="profile-back" onClick={onDashboard}><ArrowLeft size={15}/> Back to questions</button><div className="profile-layout">
    <aside className="profile-identity"><div className="profile-avatar">{user.name.slice(0,1).toUpperCase()}</div><h1>{user.fullName}</h1><p className="profile-handle">@{user.username}</p><span className="profile-profession">{user.profession}</span><button className="secondary-button" onClick={onEdit}>Edit profile</button><div className="profile-about"><h2>About me</h2><dl><div><dt>Full name</dt><dd>{user.fullName}</dd></div><div><dt>Age</dt><dd>{user.age}</dd></div><div><dt>Profession</dt><dd>{user.profession}</dd></div><div><dt>Joined</dt><dd>{new Date(user.joinedAt).toLocaleDateString(undefined,{month:'long',year:'numeric'})}</dd></div></dl></div><p className="profile-private"><ShieldCheck size={13}/> Only you can see this profile.</p></aside>
    <div className="profile-content"><section className="profile-overview" aria-label="Your solving progress"><div className="profile-overview-title"><span className="dashboard-eyebrow">ONE QUESTION AT A TIME</span><h2>Your effort, adding up.</h2></div><div className="profile-progress-body"><div className="progress-ring" style={{'--progress-angle':`${percent*3.6}deg`}} role="img" aria-label={`${solved.length} of ${problems.length} questions solved`}><div><strong>{solved.length}</strong><small>of {problems.length} solved</small></div></div><div className="profile-levels">{['Easy','Medium','Hard'].map(level => <div key={level}><span className={`level-dot ${level.toLowerCase()}`}/><span>{level}</span><strong>{solved.filter(p=>p.difficulty===level).length}<small> / {problems.filter(p=>p.difficulty===level).length}</small></strong></div>)}</div><div className="profile-attempts"><Trophy size={22}/><strong>{history.length}</strong><span>saved submissions</span><small>{history.filter(s=>s.verdict==='Accepted').length} accepted</small></div></div></section>
      <section className="profile-activity" aria-labelledby="profile-activity-title"><h2 id="profile-activity-title">Your practice history</h2><div className="profile-activity-tabs" role="tablist" aria-label="Practice history"><button role="tab" aria-selected={tab==='solved'} onClick={()=>setTab('solved')}>Solved questions <span>{solved.length}</span></button><button role="tab" aria-selected={tab==='submissions'} onClick={()=>setTab('submissions')}>Recent submissions</button></div>
        {tab === 'solved' ? <><div className="profile-list-filters"><label className="dashboard-search"><Search size={16}/><input aria-label="Search solved questions" placeholder="Find a solved question" value={search} onChange={e=>setSearch(e.target.value)}/></label><label className="dashboard-status-select"><select aria-label="Solved question difficulty" value={difficulty} onChange={e=>setDifficulty(e.target.value)}><option value="all">All difficulties</option><option value="easy">Easy</option><option value="medium">Medium</option><option value="hard">Hard</option></select></label></div><div role="tabpanel" aria-label="Solved questions">{filtered.map(p=><button className="profile-question-row" key={p.slug} onClick={()=>onOpen(p)}><CircleCheck size={17}/><span><strong>{p.title}</strong><small>#{p.number} · {progress[p.slug].submissions.some(s=>s.verdict==='Accepted') ? 'Accepted solution' : 'Marked solved'}</small></span><span className={`difficulty-badge ${p.difficulty.toLowerCase()}`}>{p.difficulty}</span><ArrowRight size={15}/></button>)}{!filtered.length && <div className="profile-empty"><Code2 size={27}/><h3>{solved.length ? 'No matching solved questions' : 'Your first solved question is waiting.'}</h3><p>{solved.length ? 'Try a different search or difficulty.' : 'Finish a question or mark it solved, and it will appear here.'}</p>{!solved.length && <button className="primary-button" onClick={onDashboard}>Explore questions<ArrowRight size={15}/></button>}</div>}</div></> : <div role="tabpanel" aria-label="Recent submissions">{history.slice(0,50).map(s=><button className="profile-question-row submission-row" key={s.id} onClick={()=>onOpen(s.problem)}><span className={s.verdict==='Accepted'?'accepted-marker':'attempt-marker'}>{s.verdict==='Accepted'?<Check size={15}/>:<Code2 size={15}/>}</span><span><strong>{s.problem.title}</strong><small>{new Date(s.date).toLocaleString()} · {s.engine==='mysql'?'MySQL':'PostgreSQL'}</small></span><span className={s.verdict==='Accepted'?'submission-verdict accepted':'submission-verdict'}>{s.verdict}</span><ArrowRight size={15}/></button>)}{!history.length && <div className="profile-empty"><Code2 size={27}/><h3>No submissions yet.</h3><p>Submit a query to start your history.</p></div>}<p className="profile-history-note">Showing your latest {Math.min(history.length,50)} saved submissions.</p></div>}
      </section></div></div></div></main>;
}
