import React, { useMemo } from 'react';
import { ArrowRight, BookOpen, Bookmark, Check, CircleCheck, Code2, History, Layers3, Play, Target, Trophy } from 'lucide-react';
import { practiceOverview } from '../shared/questions.mjs';
import { useLeaderboard } from './use-leaderboard.mjs';
import './dashboard.css';
import './overview.css';

export default function Dashboard({ api, onLeaderboard, problems, progress, user, onOpen, onBrowse, onProfile, onSignIn, currentSlug }) {
  const {data:standings,error:standingsError}=useLeaderboard(api,{userId:user?.id});
  const overview = useMemo(()=>practiceOverview(problems,progress,currentSlug),[problems,progress,currentSlug]);
  const {solved,inProgress,bookmarked,history,next,resuming,completed}=overview;
  const percent=Math.round(solved.length/Math.max(problems.length,1)*100);
  const levels=['Easy','Medium','Hard'].map(name=>({name,questions:problems.filter(p=>p.difficulty===name),solved:solved.filter(p=>p.difficulty===name).length}));
  return <main className="overview-page"><div className="overview-inner">
    <header className="overview-heading"><div><div className="overview-kicker">YOUR WORKSPACE</div><h1>Dashboard</h1><p>{user ? `Welcome back, ${user.name.split(' ')[0]}. ` : 'Welcome to Queryroom. '}Make your next query count.</p></div><button className="primary-button" onClick={()=>onBrowse({})}><BookOpen size={16}/>Browse questions<ArrowRight size={15}/></button></header>
    <section className="overview-metrics" aria-label="Practice overview">
      <button className="overview-metric" onClick={()=>onBrowse({status:'solved'})}><span className="metric-caption">Questions solved<CircleCheck size={16}/></span><strong>{solved.length}<small> / {problems.length}</small></strong><span className="metric-bottom"><span className="metric-mini-bar"><i style={{width:`${percent}%`}}/></span>{percent}% complete</span></button>
      <button className="overview-metric" onClick={()=>onBrowse({status:'in-progress'})}><span className="metric-caption">In progress<Code2 size={16}/></span><strong>{inProgress.length}</strong><span className="metric-bottom">Continue where you left off<ArrowRight size={13}/></span></button>
      <button className="overview-metric" onClick={()=>onBrowse({bookmarked:true})}><span className="metric-caption">Bookmarked<Bookmark size={16}/></span><strong>{bookmarked.length}</strong><span className="metric-bottom">Your personal shortlist<ArrowRight size={13}/></span></button>
      <div className="overview-metric"><span className="metric-caption">Saved submissions<History size={16}/></span><strong>{history.length}</strong><span className="metric-bottom">{history.filter(s=>s.verdict==='Accepted').length} accepted submissions</span></div>
      <button className="overview-metric ranking-metric" onClick={onLeaderboard}><span className="metric-caption">Leaderboard rank<Trophy size={16}/></span><strong>{standings?.currentUser ? `#${standings.currentUser.rank}` : '—'}</strong><span className="metric-bottom">{standings?.currentUser ? `${standings.currentUser.points} points · ${standings.totalUsers} ${standings.totalUsers === 1 ? 'learner' : 'learners'}` : standingsError ? 'View leaderboard' : user ? 'Your community standing' : 'Join the community'}<ArrowRight size={13}/></span></button>
    </section>
    <div className="overview-grid">
      <section className="next-question-card" aria-labelledby="next-question-title"><div className="overview-section-label"><span><Play size={14}/>{completed?'KEEP YOUR SKILLS SHARP':resuming?'PICK UP WHERE YOU LEFT OFF':'RECOMMENDED NEXT'}</span><span className="next-number">{next ? `#${next.number}` : 'SQL'}</span></div>
        {next ? <><h2 id="next-question-title">{next.title}</h2><div className="next-question-meta"><span className={`difficulty-badge ${next.difficulty.toLowerCase()}`}>{next.difficulty}</span><span>{resuming?'Your work is saved':completed?'Revisit a completed question':'A good place to start your next session'}</span></div><p>{next.summary || 'Open the question, explore the tables, and put your SQL skills to work.'}</p><div className="next-question-bottom"><button className="primary-button" onClick={()=>onOpen(next)}>{completed?'Practise again':resuming?'Resume question':'Start question'}<ArrowRight size={15}/></button><span><Code2 size={14}/>MySQL & PostgreSQL</span></div></> : <div className="overview-empty"><h2>No questions yet</h2><p>Your next practice question will appear here.</p></div>}
      </section>
      <section className="difficulty-card" aria-labelledby="difficulty-title"><div className="overview-section-heading"><h2 id="difficulty-title">Difficulty breakdown</h2><Target size={17}/></div><p>A clear view of the ground you’ve covered.</p><div className="overview-levels">{levels.filter(level=>level.questions.length).map(level=><button key={level.name} disabled={!level.questions.length} aria-label={`Browse ${level.name} questions`} onClick={()=>onBrowse({difficulty:level.name.toLowerCase()})}><span><i className={`level-dot ${level.name.toLowerCase()}`}/>{level.name}<strong>{level.solved}<small> / {level.questions.length}</small></strong></span><span className={`level-track ${level.name.toLowerCase()}`}><i style={{width:`${level.solved/Math.max(1,level.questions.length)*100}%`}}/></span></button>)}</div><div className="difficulty-card-note">{problems.length-solved.length} questions left to explore</div></section>
      <section className="practice-collections" aria-labelledby="collections-title"><div className="overview-section-heading"><div><h2 id="collections-title">Choose your practice</h2><p>A focused collection for your next session.</p></div><Layers3 size={18}/></div><div className="collection-cards">{levels.filter(level=>level.questions.length).map(level=><button key={level.name} className={`practice-collection collection-${level.name.toLowerCase()}`} onClick={()=>onBrowse({difficulty:level.name.toLowerCase()})}><span className="collection-icon">{level.name==='Hard'?<Code2 size={19}/>:<Layers3 size={19}/>}</span><span className="collection-level">{level.name.toUpperCase()}</span><h3>{level.name==='Hard'?'Challenge yourself':level.name==='Medium'?'Build consistency':'Start with the basics'}</h3><p>{level.name==='Hard'?'Work through more demanding SQL problems.':'Strengthen your SQL, one problem at a time.'}</p><span className="collection-footer"><span>{level.solved} / {level.questions.length} solved</span><ArrowRight size={15}/></span><span className="collection-track"><i style={{width:`${level.solved/level.questions.length*100}%`}}/></span></button>)}</div></section>
      <section className="overview-activity" aria-labelledby="activity-title"><div className="overview-section-heading"><h2 id="activity-title">Recent activity</h2>{user ? <button className="overview-text-link" onClick={onProfile}>View profile<ArrowRight size={13}/></button> : <History size={17}/>}</div>{history.length ? <div className="overview-activity-list">{history.slice(0,3).map(item=><button key={item.id} onClick={()=>onOpen(item.problem)}><span className={`activity-icon ${item.verdict==='Accepted'?'accepted':''}`}>{item.verdict==='Accepted'?<Check size={14}/>:<Code2 size={14}/>}</span><span><strong>{item.problem.title}</strong><small>{item.verdict} · {new Date(item.date).toLocaleDateString(undefined,{month:'short',day:'numeric'})}</small></span><ArrowRight size={13}/></button>)}</div> : <div className="overview-empty"><span className="activity-empty-icon"><History size={23}/></span><h3>Your progress starts here</h3><p>Submit a query and your recent attempts will appear here.</p></div>}</section>
    </div>
    {!user && <aside className="overview-guest"><span><Bookmark size={16}/><span><strong>Take your progress with you.</strong> Sign in to save your work across devices.</span></span><button onClick={onSignIn}>Continue with Google<ArrowRight size={14}/></button></aside>}
    <footer className="overview-footer"><span><CircleCheck size={12}/>{user?'Progress saved to your account':'Guest progress saved in this browser'}</span><span>Small steps. Real progress.</span></footer>
  </div></main>;
}
