import React, { useEffect, useMemo, useRef } from 'react';
import { ArrowLeft, ArrowRight, Check, ChevronLeft, ChevronRight, Circle, Search, SlidersHorizontal, Star, X } from 'lucide-react';
import { defaultLibraryOptions, questionPage } from '../shared/questions.mjs';
import './dashboard.css';
import './overview.css';

export default function QuestionLibrary({problems,progress,options,onChange,onOpen,onSolved,onBookmark,onDashboard,saving=new Set()}) {
  const result=useMemo(()=>questionPage(problems,progress,options),[problems,progress,options]);
  const libraryRef=useRef(null), previousPage=useRef(result.page);
  useEffect(()=>{
    if(previousPage.current!==result.page) libraryRef.current?.scrollIntoView({block:'start'});
    previousPage.current=result.page;
  },[result.page]);
  useEffect(()=>{if(options.page!==result.page) onChange({page:result.page},true);},[options.page,result.page,onChange]);
  const filter=patch=>onChange({...patch,page:1});
  const active=options.search || options.difficulty!=='all' || options.status!=='all' || options.bookmarked;
  const pages=Array.from({length:result.pages},(_,i)=>i+1).filter(n=>n===1||n===result.pages||Math.abs(n-result.page)<=1);
  const pageButtons=[];
  pages.forEach((page,index)=>{if(index&&page-pages[index-1]>1) pageButtons.push(<span className="page-ellipsis" key={`gap-${page}`}>…</span>);pageButtons.push(<button key={page} aria-label={`Page ${page}`} aria-current={page===result.page?'page':undefined} onClick={()=>onChange({page})}>{page}</button>);});
  return <main className="question-browser"><div className="question-browser-inner">
    <header className="question-browser-heading"><div><button className="library-back" onClick={onDashboard}><ArrowLeft size={13}/>Dashboard</button><h1>SQL questions<span>{problems.length}</span></h1><p>Find your next challenge. Work through it at your own pace.</p></div><span className="library-caption">THE QUESTION LIBRARY</span></header>
    <section ref={libraryRef} className="question-library paged-library" aria-label="SQL question library">
      <div className="library-quick-tabs" role="group" aria-label="Question status">{[['all','All questions'],['unsolved','To do'],['in-progress','In progress'],['solved','Solved']].map(([value,label])=><button key={value} aria-pressed={options.status===value} onClick={()=>filter({status:value})}>{label}{value==='all'&&<span>{problems.length}</span>}{value==='solved'&&<span>{problems.filter(p=>progress[p.slug]?.solved).length}</span>}</button>)}</div>
      <div className="library-controls"><label className="dashboard-search"><Search size={16}/><input aria-label="Search questions" value={options.search} maxLength={200} placeholder="Search by title or question number" onChange={e=>filter({search:e.target.value})}/>{options.search&&<button aria-label="Clear search" onClick={()=>filter({search:''})}><X size={14}/></button>}</label><label className="dashboard-status-select"><SlidersHorizontal size={15}/><select aria-label="Filter by difficulty" value={options.difficulty} onChange={e=>filter({difficulty:e.target.value})}><option value="all">All difficulties</option>{['Easy','Medium','Hard'].map(level=><option key={level} value={level.toLowerCase()}>{level} ({problems.filter(p=>p.difficulty===level).length})</option>)}</select></label><button className={`bookmark-filter${options.bookmarked?' active':''}`} aria-pressed={options.bookmarked} onClick={()=>filter({bookmarked:!options.bookmarked})}><Star size={15} fill={options.bookmarked?'currentColor':'none'}/>Bookmarked</button></div>
      <div className="library-results-bar"><span aria-live="polite">{active?`${result.total} matching ${result.total===1?'question':'questions'}`:`${result.total} questions`}{active&&<button onClick={()=>onChange({...defaultLibraryOptions,pageSize:options.pageSize})}>Clear filters<X size={11}/></button>}</span><label>Sort by<select aria-label="Sort questions" value={options.sort} onChange={e=>filter({sort:e.target.value})}><option value="recommended">Recommended</option><option value="number">Question number</option><option value="title">Title A–Z</option><option value="difficulty">Difficulty</option></select></label></div>
      <div className="questions-table-wrap"><table className="questions-table"><thead><tr><th className="status-column">Status</th><th>Question</th><th>Difficulty</th><th className="tests-column">Tests</th><th><span className="sr-only">Bookmark</span></th><th><span className="sr-only">Open question</span></th></tr></thead><tbody>{result.items.map(p=>{const done=Boolean(progress[p.slug]?.solved),starred=Boolean(progress[p.slug]?.bookmarked),pending=saving.has(p.slug);return <tr key={p.slug}><td><button className={`solve-toggle${done?' solved':''}`} aria-label={`Mark ${p.title} ${done?'unsolved':'solved'}`} aria-pressed={done} title={done?'Mark unsolved':'Mark solved'} disabled={pending} onClick={()=>onSolved(p.slug,!done)}>{done?<Check size={16}/>:<Circle size={16}/>}</button></td><td><button className="question-title-button" onClick={()=>onOpen(p)}><span className="question-number">{p.number}</span><span>{p.title}</span></button></td><td><span className={`difficulty-badge ${p.difficulty.toLowerCase()}`}>{p.difficulty}</span></td><td className="tests-column">{p.totalTests}</td><td><button className={`question-bookmark${starred?' saved':''}`} aria-label={`${starred?'Remove bookmark from':'Bookmark'} ${p.title}`} aria-pressed={starred} disabled={pending} onClick={()=>onBookmark(p.slug)}><Star size={16} fill={starred?'currentColor':'none'}/></button></td><td><button className="open-question" aria-label={`Practise ${p.title}`} onClick={()=>onOpen(p)}><ArrowRight size={15}/></button></td></tr>;})}</tbody></table></div>
      {!result.total&&<div className="dashboard-empty"><Search size={26}/><h2>No questions match</h2><p>{options.difficulty==='easy'?'This collection currently has Medium and Hard questions.':options.bookmarked?'Bookmark a question to save it here, or adjust your filters.':'Try another search, difficulty, or status.'}</p><button className="secondary-button" onClick={()=>onChange({...defaultLibraryOptions,pageSize:options.pageSize})}>Show all questions</button></div>}
      <footer className="library-pagination"><span className="pagination-summary" aria-live="polite">Showing <strong>{result.start}–{result.end}</strong> of <strong>{result.total}</strong></span><label className="page-size-label">Rows<select aria-label="Questions per page" value={options.pageSize} onChange={e=>filter({pageSize:Number(e.target.value)})}>{[8,16,24].map(size=><option key={size} value={size}>{size}</option>)}</select></label><nav aria-label="Question pages"><button aria-label="Previous page" disabled={result.page===1} onClick={()=>onChange({page:result.page-1})}><ChevronLeft size={16}/></button>{pageButtons}<button aria-label="Next page" disabled={result.page===result.pages} onClick={()=>onChange({page:result.page+1})}><ChevronRight size={16}/></button></nav></footer>
    </section><div className="question-browser-note"><Circle size={12}/><span>Mark questions solved yourself, or submit an accepted solution to mark them automatically.</span></div>
  </div></main>;
}
